site_name: NLT-Arduino
# site_url: 

site_author: Olivier Spoor

repo_url: https://github.com/olivierspoor/arduino
edit_uri: blob/main/docs/

nav:
    - Home: index.md
#    - Introductie:
    - Lessen:
      - Drukknoppen: drukknopn.md
      - RGB-LEDlampje: rgb_led.md
      - LCD-scherm met I2C-backpack: lcd_i2c.md
#    - Voorbeelden:


theme: mkdocs